name: Build Linux Wheels
on:
  push:
  pull_request:
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Cythonize
        shell: bash
        run: |
          pip install -U pip
          pip -V
          pip install -r requirements.txt
          make cython
          #python setup.py sdist

      - name: amd64
        shell: bash
        run: |
          make linux-wheel

      - name: Upload Wheels
        uses: actions/upload-artifact@v1
        with:
          name: linux-wheels
          path: ./dist/wheelhouse/
